import Link from "next/link";
import { notFound } from "next/navigation";
import { Panel } from "@/components/dashboard/Panel";
import { SiteHeader } from "@/components/dashboard/SiteHeader";
import { getCandidateQuestions } from "@/lib/dashboardData";
import type { AwarenessStage } from "@/questionGenerator/types";

const STAGE_LABELS: Record<AwarenessStage, string> = {
  pain_only: "Pain-only (no solution ask)",
  problem_framed: "Problem-framed (solution-unaware)",
  comparing_with_criteria: "Comparing with criteria (solution-aware)",
};

const STAGE_ORDER: AwarenessStage[] = ["pain_only", "problem_framed", "comparing_with_criteria"];

export default async function QuestionsPage(
  props: PageProps<"/products/[product]/questions">
) {
  const { product } = await props.params;
  const data = await getCandidateQuestions(product);
  if (!data) notFound();

  return (
    <div className="flex flex-1 flex-col">
      <SiteHeader />
      <main className="mx-auto w-full max-w-5xl flex-1 space-y-6 px-6 py-10">
        <div>
          <Link
            href={`/products/${product}`}
            className="text-sm text-muted-foreground hover:underline"
          >
            ← Back to report
          </Link>
          <h1 className="mt-2 text-2xl font-semibold tracking-tight capitalize">
            {product} — candidate questions
          </h1>
          <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
            Generated by <code>user-question-generator</code>, not yet sent to Gemini unless
            included via <code>--include-questions</code>. Review before treating any of these
            as validated AEO probes.
          </p>
        </div>

        <Panel title="Part 1 — Hook-grounded (a floor signal, not proof of strength)">
          <div className="space-y-5">
            {data.hooks.map((hook) => {
              const questions = data.hookQuestions.filter((q) => q.hook === hook.hook);
              return (
                <div key={hook.hook} className="border-b border-border/60 pb-4 last:border-0 last:pb-0">
                  <p className="text-sm font-medium">&quot;{hook.hook}&quot;</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    {hook.source} · document frequency {hook.documentFrequency}
                  </p>
                  <ul className="mt-2 list-inside list-disc space-y-1 text-sm text-muted-foreground">
                    {questions.map((q) => (
                      <li key={q.id}>{q.text}</li>
                    ))}
                  </ul>
                </div>
              );
            })}
          </div>
        </Panel>

        <Panel title="Part 2 — Inferential (paraphrased, no site quoting — the stronger signal)">
          <div className="space-y-6">
            {data.claims.map((claim) => {
              const questions = data.inferentialQuestions.filter(
                (q) => q.problem === claim.problem
              );
              const audience = [...claim.audience.userTypes, ...claim.audience.orgTypes];
              return (
                <div key={claim.problem} className="border-b border-border/60 pb-4 last:border-0 last:pb-0">
                  <p className="text-sm font-medium">{claim.problem}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    Audience: {audience.length > 0 ? audience.join(", ") : "(none detected)"}
                  </p>
                  {STAGE_ORDER.map((stage) => {
                    const staged = questions.filter((q) => q.stage === stage);
                    if (staged.length === 0) return null;
                    return (
                      <div key={stage} className="mt-2">
                        <p className="text-xs font-medium text-muted-foreground">
                          {STAGE_LABELS[stage]}
                        </p>
                        <ul className="mt-1 list-inside list-disc space-y-1 text-sm">
                          {staged.map((q) => (
                            <li key={q.id}>{q.text}</li>
                          ))}
                        </ul>
                      </div>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </Panel>
      </main>
    </div>
  );
}
